### ISSUE TITLE
Scoped rules? More options than overlap

### ISSUE THREAD

**Issue by kirkstrobeck** [emotion-js/facepaint#4]
This https://codesandbox.io/s/4x0rk07639 shows as

```css
.css-1443u2l{background:red;}
```

https://codesandbox.io/s/mql75z4wk8 shows as 

```css
.css-1443u2l{background:red;}
```

How can I get it to show as

```css
@media(min-width: 420px) { .css-1443u2l{background:red;} }
```
